#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Progress', url: 'progress.html'}
- {name: 'Posts', url: 'read/index.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-166323516-1'

#-------------------------------
# Work Section
progress-bigcategories:
  - {title: '국비 학원' , number: '0'}
  - {title: '2020' , number: '1'}


progress-subcategories:
- {bigcategory: '0', title: '가기 전 예습' , number: '0'}
- {bigcategory: '0', title: '1달 차' , number: '1'}
- {bigcategory: '0', title: '2달 차' , number: '2'}
- {bigcategory: '0', title: '3달 차' , number: '3'}
- {bigcategory: '0', title: '4달 차' , number: '4'}
- {bigcategory: '0', title: '5달 차' , number: '5'}
#- {title: '수료 이후 - 2020' , number: '6'}

progresses:
- {category: '0', name: '그린 스크린', spec: 'Javascript', image: '0-1.PNG', file: '0-1.html'}
- {category: '0', name: '사진 필터', spec: 'Javascript', image: '0-2.PNG', file: '0-2.html'}
- {category: '1', name: '호텔 고객 관리', spec: 'Java AWT', image: '1-3.PNG', file: '1-3.html'}
- {category: '2', name: '스크롤 효과', spec: 'locomotive-scroll.js', image: '2-4.PNG', file: '2-4.html'}
- {category: '2', name: '카드 게임', spec: 'javascript', image: '2-5.PNG', file: '2-5.html'}
- {category: '2', name: '펭수 그림 일기', spec: 'svg', image: '2-6.PNG', file: '2-6.html'}
- {category: '2', name: '카메라 펭수', spec: 'CSS javascript', image: '2-7.PNG', file: '2-7.html'}
- {category: '2', name: '열공 펭수', spec: 'pure CSS drawing', image: '2-8.PNG', file: '2-8.html'}
- {category: '3', name: '개인 홈피', spec: 'Java JSP', image: '3-1.PNG', file: '3-1.html'}
- {category: '3', name: '게시판', spec: 'Spring Framework / Oracle 11g / MyBatis / JSP', image: '3-2.PNG', file: '3-2.html'}
- {category: '4', name: '쿡스타그램1', spec: '팀프로젝트 / Spring Framework / Oracle 11g / MyBatis / JSP', image: '4-1.PNG', file: '4-1.html'}
- {category: '5', name: '쿡스타그램2', spec: '팀프로젝트 / Spring Boot / MySql / JPA / Thymeleaf', image: '5-1.PNG', file: '5-1.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/kohalahal'}
- {icon: 'envelope', link: 'mailto:kohalahal@gmail.com'}
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

footer: >
  © Copyright 2020 KOHALAHAL