#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: 'about.html'}
- {name: '과제', url: 'projects.html'}
- {name: '과제', url: 'progress.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'cat', url: 'cat.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-166323516-1'

#-------------------------------
# About Section

about: >
  ## 종각 자바 국비 학원 다닌다.

  공부, 과제 모음

contact: >
  ## Contact


#-------------------------------
# Work Section

progress-categories:
- {title: '예습' , number: '0'}
- {title: '1달 차' , number: '1'}
- {title: '2달 차' , number: '2'}
- {title: '3달 차' , number: '3'}

progresses:
- {category: '0', name: '그린 스크린', image: '1.PNG', file: '0-1.html'}
- {category: '0', name: '사진 필터', image: '2.PNG', file: '0-2.html'}
- {category: '1', name: '코알라 호텔 awt', image: '3.PNG', file: '1-3.html'}
- {category: '2', name: '스크롤', image: '4.PNG', file: '2-4.html'}
- {category: '2', name: '카드 게임', image: '5.PNG', file: '2-5.html'}
- {category: '2', name: '펭수 그림일기', image: '6.PNG', file: '2-6.html'}
- {category: '2', name: '열공 펭수', image: '7.PNG', file: '2-7.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'github.com/kohalahal/github.io'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:kohalahal@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
